# Generated by Django 2.1.7 on 2019-03-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Planned ', 'Planned'), ('Inprogress', 'Inprogress'), ('Done', 'Done')], default='Planned', max_length=15, null=True),
        ),
    ]
