# Generated by Django 2.1.7 on 2019-03-13 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190313_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_by',
            new_name='creator',
        ),
    ]
