# Generated by Django 2.1.7 on 2019-03-19 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20190313_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamName', models.CharField(max_length=25, unique=True)),
                ('MemberName', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('TeamLead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teamleader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
