# Generated by Django 2.1.7 on 2019-03-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190325_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='TeamName',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
